Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Max: 250

Style/GlobalVars:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 55

Style/MixinUsage:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/NumericPredicate:
  Enabled: false